<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'voryx.thruway.topic_state_handler' shared service.

include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway-bundle\\src\\Voryx\\ThruwayBundle\\TopicStateHandler.php';

return $this->privates['voryx.thruway.topic_state_handler'] = new \Voryx\ThruwayBundle\TopicStateHandler();
