<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'thruway.client' shared service.

include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway-bundle\\src\\Voryx\\ThruwayBundle\\Client\\ClientManager.php';

return $this->services['thruway.client'] = new \Voryx\ThruwayBundle\Client\ClientManager($this, $this->parameters['voryx_thruway'], ($this->services['serializer'] ?? $this->load('getSerializerService.php')));
