<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'voryx.thruway.server' shared service.

include_once $this->targetDirs[3].'\\vendor\\thruway\\client\\src\\Peer\\PeerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Peer\\RouterInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Event\\EventSubscriberInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Peer\\Router.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Module\\RouterModuleInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Module\\RouterModule.php';
include_once $this->targetDirs[3].'\\vendor\\thruway\\client\\src\\Transport\\TransportProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Transport\\RouterTransportProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway\\src\\Transport\\AbstractRouterTransportProvider.php';
include_once $this->targetDirs[3].'\\vendor\\cboden\\ratchet\\src\\Ratchet\\ComponentInterface.php';
include_once $this->targetDirs[3].'\\vendor\\cboden\\ratchet\\src\\Ratchet\\MessageInterface.php';
include_once $this->targetDirs[3].'\\vendor\\cboden\\ratchet\\src\\Ratchet\\MessageComponentInterface.php';
include_once $this->targetDirs[3].'\\vendor\\cboden\\ratchet\\src\\Ratchet\\WebSocket\\WsServerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\thruway\\ratchet-transport\\src\\RatchetTransportProvider.php';

$this->services['voryx.thruway.server'] = $instance = new \Thruway\Peer\Router(($this->services['voryx.thruway.loop'] ?? $this->load('getVoryx_Thruway_LoopService.php')));

$instance->addTransportProvider(new \Thruway\Transport\RatchetTransportProvider($this->getParameter("voryx_thruway")["router"]["ip"], $this->getParameter("voryx_thruway")["router"]["port"]));

return $instance;
