<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'wamp_kernel' shared service.

include_once $this->targetDirs[3].'\\vendor\\voryx\\thruway-bundle\\src\\Voryx\\ThruwayBundle\\WampKernel.php';

return $this->services['wamp_kernel'] = new \Voryx\ThruwayBundle\WampKernel($this, ($this->services['serializer'] ?? $this->load('getSerializerService.php')), ($this->services['voryx.thruway.resource.mapper'] ?? $this->load('getVoryx_Thruway_Resource_MapperService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
