index:
    path: /
    controller: App\Controller\MainController::index

menu:
    path: /menu
    controller: App\Controller\BuilderController::mainMenu

Anime:
    path: /Anime/{id}/{ep}
    defaults:
        _controller: App\Controller\MainController::Anime
        id: 1
    requirements:
        id: \d+

Article:
    path: /Article/{page}
    defaults:
        _controller: App\Controller\MainController::Article

login:
    path: /profile/

register:
    path: /register/

logout:
    path: /logout

recherche:
    path: /recherche/
    defaults:
        _controller: App\Controller\MainController::recherche
