<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'voryx.thruway.loop' shared service.

include_once $this->targetDirs[3].'\\vendor\\react\\event-loop\\src\\Factory.php';

return $this->services['voryx.thruway.loop'] = \React\EventLoop\Factory::create();
