<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTAmx6ov\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTAmx6ov/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTAmx6ov.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTAmx6ov\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTAmx6ov\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TAmx6ov',
    'container.build_id' => '84452212',
    'container.build_time' => 1539773261,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTAmx6ov');
