<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9Bge1n\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9Bge1n/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN9Bge1n.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN9Bge1n\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerN9Bge1n\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'N9Bge1n',
    'container.build_id' => '42600614',
    'container.build_time' => 1543417800,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9Bge1n');
