<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfFtvMb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfFtvMb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCfFtvMb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCfFtvMb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCfFtvMb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CfFtvMb',
    'container.build_id' => '22f986c6',
    'container.build_time' => 1537230364,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfFtvMb');
